version: "3.7"
services:
  php-fpm:
    build:
      context: ./php-fpm
      dockerfile: Dockerfile
    image: local-php:7.2-fpm
    container_name: php-fpm
    restart: unless-stopped
    working_dir: ${APP_CONTAINER}
    volumes:
      - ${APP_HOST}:${APP_CONTAINER}
      - ./php-fpm/local.ini:/usr/local/etc/php/conf.d/local.ini
    ports:
      - "9000:9000"

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - ./mysql/conf:/etc/mysql/conf.d
      - ./mysql/dumps:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "81:81"
    volumes:
      - ${APP_HOST}:${APP_CONTAINER}
      - ./nginx/sites/:/etc/nginx/conf.d
    depends_on:
      - php-fpm

  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  node:
    image: node:10.21.0
    container_name: node
    volumes:
      - ${APP_HOST}:${APP_CONTAINER}
    working_dir: ${APP_CONTAINER}
