version: "3.8"

services:
  php-fpm:
    build:
      context: ./php-fpm
      dockerfile: Dockerfile
      args:
        IMAGE: ${PHP_IMAGE}
    image: ${PHP_IMAGE}
    container_name: ${APP_PREFIX}-php-fpm
    restart: unless-stopped
    working_dir: ${APP_CONTAINER}
    volumes:
      - ${APP_HOST}:${APP_CONTAINER}
      - ./php-fpm/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./php-fpm/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./php-fpm/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    extra_hosts:
      - "dockerhost:172.18.0.2"
      - "autoxml.tech:172.18.0.2"
      - "img.tech:172.18.0.2"

  mysql:
    image: ${MYSQL_IMAGE}
    container_name: ${APP_PREFIX}-mysql
    restart: unless-stopped
    command:
      - --sort_buffer_size=1073741824
      - --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./mysql:/etc/mysql/conf.d
    ports:
      - "3306:3306"

  nginx:
    image: ${NGINX_IMAGE}
    container_name: ${APP_PREFIX}-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${APP_HOST}:${APP_CONTAINER}
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - php-fpm

  redis:
    image: ${REDIS_IMAGE}
    container_name: ${APP_PREFIX}-redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  node:
    image: ${NODE_IMAGE}
    container_name: ${APP_PREFIX}-node
    volumes:
      - ${APP_HOST}:${APP_CONTAINER}
    working_dir: ${APP_CONTAINER}
