version: "3.7"
services:
  php-fpm:
    build:
      args:
        USER: laravel
        UID: 1000
        NODE_VERSION: 10.21.0
      context: ./php-fpm
      dockerfile: Dockerfile
    image: local-php:7.2-fpm
    container_name: php-fpm
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - /home/mirlan/www:/var/www
    ports:
      - "9000:9000"

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - ./mysql/conf:/etc/mysql/conf.d
      - ./mysql/dumps:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "81:81"
    volumes:
      - /home/mirlan/www:/var/www
      - ./nginx/sites/:/etc/nginx/conf.d
    depends_on:
      - php-fpm

  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"